import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Main from '../components/Main'
import About from '../components/About'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Prado Calçados</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  
      <Main heading='BEM VINDO A PRADO CALÇADOS' message='Qualidade' message1='e Tradição'/> 
      <About />
    </div>
  )
}
